export type Course = {
  grade: string;
  code: string;
  name: string;
  credit: string;
};

export type Major = "ai" | "elec" | "mech" | "space" | "energy" | "energy_re" | "energy_cv" | "nursing" | "physics" | "math" | "chem" | "stat" | "geo_geol" | "geo_astro" | "geo_ocean" | "kor_lit" | "eng_lit" | "fre_lit" | "ger_lit" | "chi_lit" | "history" | "philosophy" | "anthro" | "jpn_lit" | "kor_clas" | "rus_lit" | "poli_sci" | "sociology" | "geography" | "doc_info" | "psychology" | "business" | "econ" | "polymer" | "env_eng" | "textile" | "metal_mat" | "agri_civil" | "plant_sci" | "env_life_chem" | "food_biotech" | "food_mat" | "food_app" | "plant_med" | "food_econ" | "smart_bio_mech" | "edu" | "kor_edu" | "eng_edu" | "ethics_edu" | "math_edu" | "home_edu" | "ger_edu" | "fre_edu" | "history_edu" | "geo_edu" | "social_edu" | "phys_edu" | "chem_edu" | "bio_edu" | "earth_edu" | "clothing" | "food_nutrition" | "child_dev" | "child_edu" | "pub_admin" | "pub_policy" | "bio_med_eng" | "robot_smart" | "h2_energy" | "smart_mobility" | "innov_pharma" | "bio_med_fusion" | "robotics" | "adv_tech_self1" | "adv_tech_self2" | "auto_fusion" | "ai_conv" | "bio_med_conv" | "robot_conv" | "h2_conv" | "cs_know" | "cs_sw_conv" | "cs_sys_sw" | "cs_global_sw" | "cs_platform" | "cs_data" | "cs_human_ai" | "cs_ai_comp" | "cs_deep" | "cs_adv" | "bio_eng" | "new_mat" | "new_mat_div" | "new_mat_elec" | "bio_sum_sojae" | "sj_civil_disaster" | "sj_civil_env" | "sj_smart_auto" | "sj_mat_nano" | "sj_echem_nano" | "sj_aerospace" | "sj_plant_sys" | "sj_mat_energy" | "sj_echem_energy" | "sj_precision_mech" | "sj_food_service" | "sj_textile" | "sj_fashion" | "sj_ind_mech" | "sj_civil_disaster_dept" | "sj_env_safety" | "sj_dental_hyg" | "sj_sw" | "sj_gis" | "sj_smart_plant" | "sj_auto" | "sj_nano_mat" | "sj_energy_chem" | "sj_livestock" | "sj_bio_app" | "sj_eco_tour" | "sj_livestock_biotech" | "sj_insect" | "sj_tourism" | "sj_horse" | "sj_livestock_startup" | "sj_forest_eco" | "sj_plant_res" | "sj_phys_edu" | "sj_animal_biotech" | "sj_phys_edu_major" | "sj_health_sports" | "sj_eco_auto" | "chem_eng" | "social_welfare_micro" | "social_welfare_macro" | "social_welfare" | "appli_chem" | "media_commu" | "medical" | "medical-semi" | "dentist" | "dentist-semi" | "eleceng" | "appli_chem_a" | "appli_chem_b" | "appli_chem_major" | "appli_chem_eng" | "computer_edu" | "forestry" | "forest_prod_eng" | "landscape_arch" | "music" | "korean_music2" | "art" | "design" | "digital_art" | "biology" | "PPE" | "wonye" | "sj_leisure_sports" | "build" | "build2" | "medicine1";

export const MAJOR_LABELS: Record<Major, string> = {
  ai: "전자공학부 인공지능전공",
  home_edu: "가정교육과",
  nursing: "간호학과",
  build: "건축학부-건축공학전공",
  build2: "건축학부-건축학전공",
  business: "경영학부",
  econ: "경제통상학부",
  anthro: "고고인류학과",
  polymer: "고분자공학과",
  edu: "교육학과",
  korean_music2: "국악학과",
  kor_edu: "국어교육과",
  kor_lit: "국어국문학과",
  metal_mat: "금속재료공학과",
  mech: "기계공학부",
  rus_lit: "노어노문학과",
  agri_civil: "농업토목공학과",
  ger_lit: "독어독문학과",
  design: "디자인학과",
  digital_art: "디지털아트융합전공",
  robotics: "로봇공학과",
  robot_smart: "로봇및스마트시스템공학전공",
  doc_info: "문헌정보학과",
  phys_edu: "물리교육과",
  physics: "물리학과",
  media_commu: "미디어커뮤니케이션학과",
  art: "미술학과",
  bio_sum_sojae: "바이오섬유소재학과",
  fre_lit: "불어불문학과",
  history: "사학과",
  social_welfare_macro: "사회복지거시전공",
  social_welfare_micro: "사회복지미시전공",
  social_welfare: "사회복지학부",
  sociology: "사회학과",
  forest_prod_eng: "산림과학·조경학부-임산공학전공",
  forestry: "산림과학·조경학부-임학전공",
  landscape_arch: "산림과학·조경학부-조경학전공",
  bio_eng: "생명공학부",
  bio_edu: "생물교육과",
  biology: "생물학과",
  textile: "섬유시스템공학과",
  h2_energy: "수소및신재생에너지전공",
  math: "수학과",
  math_edu: "수학교육과",
  smart_mobility: "스마트모빌리티공학과",
  smart_bio_mech: "스마트생물산업기계공학과",
  plant_med: "식물의학과",
  food_biotech: "식품공학부-식품생물공학전공",
  food_mat: "식품공학부-식품소재공학전공",
  food_app: "식품공학부-식품응용공학전공",
  food_nutrition: "식품영양학과",
  food_econ: "식품자원경제학과",
  new_mat: "신소재공학과(24학번~)",
  new_mat_div: "신소재공학부(~23학번)",
  new_mat_elec: "신소재공학부-전자재료공학전공(~23학번)",
  psychology: "심리학과",
  child_dev: "아동학부-아동가족학전공",
  child_edu: "아동학부-아동교육전공",
  medicine1: "약학과",
  energy: "에너지공학부",
  energy_re: "에너지공학부-신재생에너지전공",
  energy_cv: "에너지공학부-에너지변환전공",
  history_edu: "역사교육과",
  eng_edu: "영어교육과",
  eng_lit: "영어영문학과",
  space: "우주공학부",
  wonye: "원예과학과",
  ger_edu: "유럽어교육학부-독어교육전공",
  fre_edu: "유럽어교육학부-불어교육전공",
  ethics_edu: "윤리교육과",
  robot_conv: "융합학부-로봇및스마트시스템공학전공",
  h2_conv: "융합학부-수소및신재생에너지전공",
  bio_med_conv: "융합학부-의생명융합공학전공",
  ai_conv: "융합학부-인공지능전공",
  music: "음악학과",
  plant_sci: "응용생명과학부-식물생명과학전공",
  env_life_chem: "응용생명과학부-환경생명화학전공",
  appli_chem: "응용화학공학부",
  appli_chem_major: "응용화학공학부-응용화학전공",
  appli_chem_eng: "응용화학공학부-화학공학전공",
  appli_chem_a: "응용화학공학부A",
  appli_chem_b: "응용화학공학부B",
  clothing: "의류학과",
  bio_med_fusion: "의생명융합공학과",
  bio_med_eng: "의생명융합공학전공",
  "medical-semi": "의예과",
  medical: "의학과",
  social_edu: "일반사회교육과",
  jpn_lit: "일어일문학과",
  auto_fusion: "자율시스템 융합전공",
  eleceng: "전기공학과",
  elec: "전자공학부",
  computer_edu: "정보컴퓨터교육과",
  PPE: "정치-경제-철학(PPE)융합전공",
  poli_sci: "정치외교학과",
  chi_lit: "중어중문학과",
  earth_edu: "지구과학교육과",
  geo_edu: "지리교육과",
  geography: "지리학과",
  geo_geol: "지질학전공",
  geo_astro: "천문대기과학전공",
  philosophy: "철학과",
  adv_tech_self1: "첨단기술융합대학 자율학부1",
  adv_tech_self2: "첨단기술융합대학 자율학부2",
  "dentist-semi": "치의예과",
  dentist: "치의학과",
  cs_global_sw: "컴퓨터학부-글로벌소프트웨어융합전공",
  cs_data: "컴퓨터학부-데이터과학전공",
  cs_sys_sw: "컴퓨터학부-시스템소프트웨어전공",
  cs_deep: "컴퓨터학부-심화컴퓨팅전공",
  cs_sw_conv: "컴퓨터학부-융합소프트웨어전공",
  cs_human_ai: "컴퓨터학부-인간중심소프트웨어전공",
  cs_ai_comp: "컴퓨터학부-인공지능컴퓨팅전공",
  cs_know: "컴퓨터학부-지식정보컴퓨팅전공",
  cs_adv: "컴퓨터학부-첨단컴퓨팅연구전공",
  cs_platform: "컴퓨터학부-플랫폼소프트웨어전공",
  stat: "통계학과",
  kor_clas: "한문학과",
  geo_ocean: "해양학전공",
  pub_admin: "행정학부-공공관리전공",
  pub_policy: "행정학부-공공정책전공",
  innov_pharma: "혁신신약학과",
  chem_eng: "화학공학과(~25학번)",
  chem: "화학과",
  chem_edu: "화학교육과",
  env_eng: "환경공학과",
  sj_health_sports: "[상주]건강운동관리전공",
  sj_civil_disaster_dept: "[상주]건설방재공학과",
  sj_civil_disaster: "[상주]건설방재공학전공(~22학번)",
  sj_civil_env: "[상주]건설환경공학전공(~22학번)",
  sj_insect: "[상주]곤충생명과학과",
  sj_tourism: "[상주]관광학과",
  sj_nano_mat: "[상주]나노신소재공학과",
  sj_animal_biotech: "[상주]동물생명공학과",
  sj_leisure_sports: "[상주]레저스포츠학과(~22학번)",
  sj_horse: "[상주]말특수동물학과",
  sj_forest_eco: "[상주]산림생태보호학과",
  sj_ind_mech: "[상주]산업기계공학과",
  sj_bio_app: "[상주]생물응용전공(~21학번)",
  sj_eco_tour: "[상주]생태관광전공(~21학번)",
  sj_textile: "[상주]섬유공학전공",
  sj_sw: "[상주]소프트웨어학과",
  sj_smart_plant: "[상주]스마트플랜트공학과",
  sj_plant_res: "[상주]식물자원학과",
  sj_food_service: "[상주]식품외식산업학과",
  sj_mat_nano: "[상주]신소재공학전공(~22학번)",
  sj_mat_energy: "[상주]신소재공학전공(~23학번)",
  sj_echem_nano: "[상주]에너지화공전공(~22학번)",
  sj_energy_chem: "[상주]에너지화학공학과",
  sj_echem_energy: "[상주]에너지화학공학전공(~23학번)",
  sj_gis: "[상주]위치정보시스템학과",
  sj_auto: "[상주]자동차공학과",
  sj_precision_mech: "[상주]정밀기계공학과",
  sj_smart_auto: "[상주]지능형자동차전공(~25학번)",
  sj_phys_edu: "[상주]체육학과(~23학번)",
  sj_phys_edu_major: "[상주]체육학전공",
  sj_livestock_biotech: "[상주]축산생명공학과(~22학번)",
  sj_livestock_startup: "[상주]축산창업전공(~22학번)",
  sj_livestock: "[상주]축산학과",
  sj_dental_hyg: "[상주]치위생학과",
  sj_eco_auto: "[상주]친환경자동차전공(~25학번)",
  sj_fashion: "[상주]패션디자인전공",
  sj_plant_sys: "[상주]플랜트시스템전공(~22학번)",
  sj_aerospace: "[상주]항공위성시스템전공(~22학번)",
  sj_env_safety: "[상주]환경안전공학과",

};

export const MAJOR_META: Record<Major, { deptCd: string; baseDeptCd?: string }> = {
  ai:        { deptCd: "1O0109" },
  elec:      { deptCd: "1O01" },
  mech:      { deptCd: "1601" },
  space:     { deptCd: "1003" },
  energy:    { deptCd: "1611" },
  energy_re: { deptCd: "161101", baseDeptCd: "1611" },
  energy_cv: { deptCd: "161102", baseDeptCd: "1611" },
  nursing: { deptCd: "1C01" },
  physics: { deptCd: "130A" },
  math: { deptCd: "1301" },
  chem: { deptCd: "1302" },
  stat: { deptCd: "1304" },
  geo_geol: { deptCd: "130Q01", baseDeptCd: "130Q" },
  geo_astro: { deptCd: "130Q02", baseDeptCd: "130Q" },
  geo_ocean: { deptCd: "130Q03", baseDeptCd: "130Q" },
  kor_lit: { deptCd: "1101" },
  eng_lit: { deptCd: "1102" },
  fre_lit: { deptCd: "1103" },
  ger_lit: { deptCd: "1104" },
  chi_lit: { deptCd: "1105" },
  history: { deptCd: "1106" },
  philosophy: { deptCd: "1107" },
  anthro: { deptCd: "1108" },
  jpn_lit: { deptCd: "1109" },
  kor_clas: { deptCd: "110A" },
  rus_lit: { deptCd: "110B" },
  poli_sci: { deptCd: "1201" },
  sociology: { deptCd: "1202" },
  geography: { deptCd: "1203" },
  doc_info: { deptCd: "1204" },
  psychology: { deptCd: "1205" },
  business: { deptCd: "1403" },
  econ: { deptCd: "1404" },
  polymer: { deptCd: "1605" },
  env_eng: { deptCd: "1606" },
  textile: { deptCd: "1607" },
  metal_mat: { deptCd: "1617" },
  agri_civil: { deptCd: "1703" },
  plant_sci: { deptCd: "170B01", baseDeptCd: "170B" },
  env_life_chem: { deptCd: "170B04", baseDeptCd: "170B" },
  food_biotech: { deptCd: "170P01", baseDeptCd: "170P" },
  food_mat: { deptCd: "170P02", baseDeptCd: "170P" },
  food_app: { deptCd: "170P03", baseDeptCd: "170P" },
  plant_med: { deptCd: "170Y" },
  food_econ: { deptCd: "170Z" },
  smart_bio_mech: { deptCd: "1711" },
  edu: { deptCd: "1901" },
  kor_edu: { deptCd: "1902" },
  eng_edu: { deptCd: "1903" },
  ethics_edu: { deptCd: "1907" },
  math_edu: { deptCd: "1908" },
  home_edu: { deptCd: "190A" },
  ger_edu: { deptCd: "190D01", baseDeptCd: "190D" },
  fre_edu: { deptCd: "190D02", baseDeptCd: "190D" },
  history_edu: { deptCd: "190E" },
  geo_edu: { deptCd: "190F" },
  social_edu: { deptCd: "190G" },
  phys_edu: { deptCd: "190H" },
  chem_edu: { deptCd: "190I" },
  bio_edu: { deptCd: "190J" },
  earth_edu: { deptCd: "190K" },
  clothing: { deptCd: "1B03" },
  food_nutrition: { deptCd: "1B04" },
  child_dev: { deptCd: "1B0701", baseDeptCd: "1B07" },
  child_edu: { deptCd: "1B0702", baseDeptCd: "1B07" },
  pub_admin: { deptCd: "1S0101", baseDeptCd: "1S01" },
  pub_policy: { deptCd: "1S0102", baseDeptCd: "1S01" },
  bio_med_eng: { deptCd: "100101", baseDeptCd: "1001" },
  robot_smart: { deptCd: "100102", baseDeptCd: "1001" },
  h2_energy: { deptCd: "100103", baseDeptCd: "1001" },
  smart_mobility: { deptCd: "1002" },
  innov_pharma: { deptCd: "1004" },
  bio_med_fusion: { deptCd: "1005" },
  robotics: { deptCd: "1006" },
  adv_tech_self1: { deptCd: "1007" },
  adv_tech_self2: { deptCd: "1008" },
  auto_fusion: { deptCd: "1009" },
  ai_conv: { deptCd: "1T0101", baseDeptCd: "1T01" },
  bio_med_conv: { deptCd: "1T0102", baseDeptCd: "1T01" },
  robot_conv: { deptCd: "1T0103", baseDeptCd: "1T01" },
  h2_conv: { deptCd: "1T0104", baseDeptCd: "1T01" },
  cs_know: { deptCd: "100201", baseDeptCd: "1002" },
  cs_sw_conv: { deptCd: "100202", baseDeptCd: "1002" },
  cs_sys_sw: { deptCd: "100203", baseDeptCd: "1002" },
  cs_global_sw: { deptCd: "100204", baseDeptCd: "1002" },
  cs_platform: { deptCd: "100205", baseDeptCd: "1002" },
  cs_data: { deptCd: "100206", baseDeptCd: "1002" },
  cs_human_ai: { deptCd: "100207", baseDeptCd: "1002" },
  cs_ai_comp: { deptCd: "100208", baseDeptCd: "1002" },
  cs_deep: { deptCd: "100209", baseDeptCd: "1002" },
  cs_adv: { deptCd: "100210", baseDeptCd: "1002" },  bio_eng: { deptCd: "130M" },
  new_mat: { deptCd: "1618" },
  new_mat_div: { deptCd: "1609" },
  new_mat_elec: { deptCd: "160904" },
  bio_sum_sojae: { deptCd: "170Q" },
  sj_civil_disaster: { deptCd: "1U0101", baseDeptCd: "1U01" },
  sj_civil_env: { deptCd: "1U0102", baseDeptCd: "1U01" },
  sj_smart_auto: { deptCd: "1U0302", baseDeptCd: "1U03" },
  sj_mat_nano: { deptCd: "1U0701", baseDeptCd: "1U07" },
  sj_echem_nano: { deptCd: "1U0703", baseDeptCd: "1U07" },
  sj_aerospace: { deptCd: "1U0I01", baseDeptCd: "1U0I" },
  sj_plant_sys: { deptCd: "1U0I02", baseDeptCd: "1U0I" },
  sj_mat_energy: { deptCd: "1U0N01", baseDeptCd: "1U0N" },
  sj_echem_energy: { deptCd: "1U0N03", baseDeptCd: "1U0N" },
  sj_precision_mech: { deptCd: "1U02" },
  sj_food_service: { deptCd: "1U08" },
  sj_textile: { deptCd: "1U0A01" },
  sj_fashion: { deptCd: "1U0A02" },
  sj_ind_mech: { deptCd: "1U0D" },
  sj_civil_disaster_dept: { deptCd: "1U0F" },
  sj_env_safety: { deptCd: "1U0G" },
  sj_dental_hyg: { deptCd: "1U0J" },
  sj_sw: { deptCd: "1U0K" },
  sj_gis: { deptCd: "1U0L" },
  sj_smart_plant: { deptCd: "1U0M" },
  sj_auto: { deptCd: "1U0O" },
  sj_nano_mat: { deptCd: "1U0P" },
  sj_energy_chem: { deptCd: "1U0Q" },
  sj_livestock: { deptCd: "1L04" },
  sj_bio_app: { deptCd: "1L0601" },
  sj_eco_tour: { deptCd: "1L0603" },
  sj_livestock_biotech: { deptCd: "1L09" },
  sj_insect: { deptCd: "1L0A" },
  sj_tourism: { deptCd: "1L0B" },
  sj_horse: { deptCd: "1L10" },
  sj_livestock_startup: { deptCd: "1L11" },
  sj_forest_eco: { deptCd: "1L12" },
  sj_plant_res: { deptCd: "1L13" },
  sj_phys_edu: { deptCd: "1L14" },
  sj_animal_biotech: { deptCd: "1L15" },
  sj_phys_edu_major: { deptCd: "1L1601" },
  sj_health_sports: { deptCd: "1L1602" },
  sj_eco_auto: { deptCd: "1U0301", baseDeptCd: "1U03" },
  chem_eng: { deptCd: "1604" },
  social_welfare_micro: { deptCd: "120901", baseDeptCd: "1209" },
  social_welfare_macro: { deptCd: "120902", baseDeptCd: "1209" },
  social_welfare: { deptCd: "1209" },
  appli_chem: { deptCd: "1612" },
  media_commu: { deptCd: "120D" },
  medical: { deptCd: "1F01" },
  "medical-semi": { deptCd: "1F04" },
  dentist: { deptCd: "1G01" },
  "dentist-semi": { deptCd: "1G02" },
  eleceng: { deptCd: "1O03" },
  appli_chem_a: { deptCd: "1612001", baseDeptCd: "1612" },
  appli_chem_b: { deptCd: "1612002", baseDeptCd: "1612" },
  appli_chem_major: { deptCd: "161201", baseDeptCd: "1612" },
  appli_chem_eng: { deptCd: "161202", baseDeptCd: "1612" },
  computer_edu: { deptCd: "191I" },
  forestry: { deptCd: "170S01", baseDeptCd: "170S" },
  forest_prod_eng: { deptCd: "170S02", baseDeptCd: "170S" },
  landscape_arch: { deptCd: "170S03", baseDeptCd: "170S" },
  music: { deptCd: "1801" },
  korean_music2: { deptCd: "1803" },
  art: { deptCd: "1804" },
  design: { deptCd: "1806" },
  digital_art: { deptCd: "1807" },
  biology: { deptCd: "1309" },
  PPE: { deptCd: "110K" },
  wonye: { deptCd: "170O" },
  sj_leisure_sports: { deptCd: "1L05" },
  build: { deptCd: "160I01" },
  build2: { deptCd: "160I02" },
  medicine1: { deptCd: "1Q02" },

};

/** /public/courses/{major}/{entryYear}.json 에서 과목 목록 fetch (클라이언트용) */
export async function fetchCoursesByYear(major: Major, entryYear: number): Promise<Course[]> {
  try {
    const res = await fetch(`/courses/${major}/${entryYear}.json`);
    if (!res.ok) return [];
    return await res.json() as Course[];
  } catch {
    return [];
  }
}

export const ENTRY_YEAR_MIN = 2021;
export const ENTRY_YEAR_MAX = 2050;

export const SEMESTER_CODES: Record<string, string> = {
  "1": "CMBS001400001",
  "2": "CMBS001400002",
  "s": "CMBS001400004",
  "w": "CMBS001400003",
};

export function parseSemester(text: string): { year: string; semCode: string } | null {
  const m = text.trim().match(/^(\d{4})-([12sw])$/i);
  if (!m) return null;
  const semCode = SEMESTER_CODES[m[2].toLowerCase()];
  return { year: m[1], semCode };
}
